features
VolffS/test-task pull request #1
Opened 2024-03-25 03:47 UTC by VolffS

2024-03-26 17:52 UTC, xDSUP requested changes

2024-03-26 17:52 UTC, xDSUP commented on src/type/i-authorization-user.ts
> +export interface IAuthorizationUser {
I в названии интерфейсов - признак плохого нейминга)

2024-03-26 17:52 UTC, xDSUP commented on src/type/i-comment.ts
> +    "postId": number,
Зачем тут кавычки

2024-03-26 17:52 UTC, xDSUP commented on src/store/state-authorization-user-slice.ts
> +    "username": "Anonymous",
Если авторизации нет, то и тут ничего не должно быть

2024-03-26 17:52 UTC, xDSUP commented on src/hooks/use-actions.ts
> +export const useActions = () => {
нейминг слишком общий, тут же акшены связанные с авторизацией лежат

2024-03-26 17:52 UTC, xDSUP commented on src/components/hamburger-user/hamburger-user.tsx
> +            {!isAuthorization && < AuthorizationUser/>}
Вот эта штука должна быть не в этом компоненте, а выше. Тк кнопка - войти, значит авторизованного польз нет. ну и там либо войти, / либо выйти как раз

2024-03-26 17:52 UTC, xDSUP commented on src/components/form-authorization/form-authorization.tsx
> +                                    <Input placeholder="Ketty2646" {...field} />
А нормальный плейсхолдер можно?) Просто я пытался ввести вот эти значения и меня не пускало(

2024-03-26 17:52 UTC, xDSUP commented on src/components/form-authorization/form-authorization.tsx
> +                        <p className="error-text">Не верный логин или пароль</p>}
ввожу email и userName, а говорит, что пароль неверный.

2024-03-26 17:52 UTC, xDSUP commented on src/components/form-authorization/form-authorization.tsx
> +        message: "Username не должен быть пустым",
круто, что ты zod нашел сам)

2024-03-26 17:52 UTC, xDSUP commented on src/components/author/author.tsx
> +export const Author = () => {
Кста,вот это хороший и прозрачный компонент. Рекомендация, такие компоненты, которые рисуют целые страницы принятно класть не в components, а в каталог pages

2024-03-26 17:52 UTC, xDSUP commented on src/components/authorization-user/authorization-user.tsx
> +export const AuthorizationUser = () => {
Нейминг( Это диалог, а значит лучше назвать Auth...UserDialog.

2024-03-26 17:52 UTC, xDSUP commented on src/components/avatar-user/avatar-user.tsx
> +          <img src={avatarGif}  alt=""/>
А чего альт пустой?)

2024-03-26 17:52 UTC, xDSUP commented on src/components/burger-menu/burger-menu.tsx
> +                        <Link className={classLink} to={isAuthorization ? `/about-me/${user.id}` : ""}
это вообще скрыть из разметки без авторизации. Ты ж когда не авторизован на других сайтах, ты обычно невидишь недоступные разделы.

2024-03-26 17:52 UTC, xDSUP commented on src/components/burger-menu/burger-menu.tsx
> +    const classLink = `hamburger-link ${isAuthorization ? "link-active" : "link-disabled"}`
оч далеко от места применения, + используется один раз, можно было прям по месту сделать

2024-03-26 17:52 UTC, xDSUP commented on src/components/burger-menu/burger-menu.tsx
> +    const {user, isAuthorization}: IAuthorizationUser = useSelector<RootState>(state => state.stateUserSlice)
в целом можно еще сделать selectors.ts и сделать отдельный селектор для каждого слайса, чтобы вот это не дублировать везде. 

const useAuthStoreSelector = useSelector<RootState>(state => state.stateUserSlice)

2024-03-26 17:52 UTC, xDSUP commented on src/components/comment-list/comments-list.tsx
> +                {!isLoading && stateLoader.shutdownLoader()}
Я правильно понимаю, что ты просто выключаешь тут stateLoader.isLoader? Код из-за этого вообще не прозрачный становится. Мб тут какой-нибудь useEffect прикрутить для этого.  А

блин, ты добавил задержку отображения лоадера сюда... тут подумать бы ещё. Чет выглядит так себек

2024-03-26 17:52 UTC, xDSUP commented on src/components/post-list/post-list.tsx
> +                {stateLoader.isLoader && <LoaderAllSpace/>}
ну, тут дублирование, как в со списке комментов. Надо чет придумать

2024-03-26 17:52 UTC, xDSUP commented on src/components/comment-list/comments-list.tsx
> +                {stateLoader.isLoader && <LoaderMini/>}
вот эти все штуки можно вынести наверх и код станет намного проще

2024-03-26 17:54 UTC, xDSUP commented on src/components/comment-list/comments-list.tsx
> +                {stateLoader.isLoader && <LoaderMini/>}
![image](https://github.com/VolffS/test-task/assets/24694817/e0189459-8555-49e5-8593-6ffce9440b49)

2024-03-26 18:00 UTC, xDSUP commented on src/components/user/user.tsx
> +                    {stateLoader.isLoader && <LoaderAllSpace/>}
ну тут таже штука с ошибкой и лоадером, как я показывал

2024-03-26 18:01 UTC, xDSUP commented on src/components/user-posts/user-posts.tsx
> +              {stateLoader.isLoader && <LoaderMini/>}
таже штука

2024-03-26 18:01 UTC, xDSUP commented on src/components/post-list/post-list.tsx
> +                {stateLoader.isLoader && <LoaderAllSpace/>}
таже штука

2024-03-26 18:31 UTC, xDSUP commented on src/api/api.ts
> +        getPosts: build.query({
Нет типизации, должно быть query<Post[], undefined> . Посмотри почему именно такие аргументы я привел тут и разберись, какие добавить ниже

2024-03-26 18:32 UTC, xDSUP commented on src/hooks/use-deferred-loader.ts
> +    const shutdownLoader = (): void => {
Вот это все фигнюшка, убирай вообще это useDeferredLoader. В след комменте покажу, как лучше вернуть результат с искусственной задержкой

2024-03-26 18:37 UTC, VolffS commented on src/store/state-authorization-user-slice.ts
> +    "username": "Anonymous",
Хочу уточнить ты имеешь ввиду 
```
{
    "id": 0,
    "name": "",
    "username": "",
    "email": "",
    "phone": "",
}
```
Или
`{}`

2024-03-26 18:40 UTC, xDSUP commented on src/store/state-authorization-user-slice.ts
> +    "username": "Anonymous",
вообще initialUser = null)

2024-03-26 18:42 UTC, xDSUP commented on src/api/api.ts
> +            query: () => '/posts'
В общ, есть тут такая штука, как transformResponse, который преобразует ответ во что-то другое, и эта штука может вернуть промис

2024-03-26 18:43 UTC, xDSUP commented on src/api/api.ts
> +            query: () => '/posts'
Разберись опять же, кто такой Result в моем примере, и функцию в такую виде можно сразу подставить во все твои запросы и они будут отдавать ответ с задержкой в 500мс

2024-03-27 13:55 UTC, VolffS commented on src/components/burger-menu/burger-menu.tsx
> +    const {user, isAuthorization}: IAuthorizationUser = useSelector<RootState>(state => state.stateUserSlice)
Не нашёл ничего по поводу вынеса всего `useSelector`. 
Нашёл про вынос этой части `state => state.stateUserSlice`

2024-03-27 14:37 UTC, VolffS commented on src/api/api.ts
> +        getPosts: build.query({
Написал так как будто там смерть) Done
Для незнакомцев. Мало-ли кто сюда забредёт
[](https://redux-toolkit.js.org/rtk-query/usage-with-typescript)

![image](https://github.com/VolffS/test-task/assets/78679100/0db230b8-c7db-49a6-a90a-0a3f54807ef5)

2024-03-27 17:15 UTC, VolffS commented on src/api/api.ts
> +            query: () => '/posts'
Done

2024-03-27 17:15 UTC, VolffS commented on src/hooks/use-deferred-loader.ts
> +    const shutdownLoader = (): void => {
Done

2024-03-27 17:15 UTC, VolffS commented on src/components/post-list/post-list.tsx
> +                {stateLoader.isLoader && <LoaderAllSpace/>}
Done

2024-03-27 17:15 UTC, VolffS commented on src/components/user-posts/user-posts.tsx
> +              {stateLoader.isLoader && <LoaderMini/>}
Done

2024-03-27 17:15 UTC, VolffS commented on src/components/user/user.tsx
> +                    {stateLoader.isLoader && <LoaderAllSpace/>}
Done

2024-03-27 17:15 UTC, VolffS commented on src/components/comment-list/comments-list.tsx
> +                {stateLoader.isLoader && <LoaderMini/>}
Done

2024-03-27 17:15 UTC, VolffS commented on src/components/burger-menu/burger-menu.tsx
> +    const {user, isAuthorization}: IAuthorizationUser = useSelector<RootState>(state => state.stateUserSlice)
Сделал как нашёл инфу 
Done

2024-03-27 17:15 UTC, VolffS commented on src/components/burger-menu/burger-menu.tsx
> +    const classLink = `hamburger-link ${isAuthorization ? "link-active" : "link-disabled"}`
Это правда только при условии использовании реализации твоего коммента выше

2024-03-27 17:15 UTC, VolffS commented on src/components/burger-menu/burger-menu.tsx
> +                        <Link className={classLink} to={isAuthorization ? `/about-me/${user.id}` : ""}
Не везде так. 
Я сообщаю что такая функция есть. Но она ему недоступна без авторизации

2024-03-27 17:15 UTC, VolffS commented on src/hooks/use-actions.ts
> +export const useActions = () => {
done

2024-03-27 17:15 UTC, VolffS commented on src/store/state-authorization-user-slice.ts
> +    "username": "Anonymous",
done

2024-03-27 17:16 UTC, VolffS commented on src/type/i-comment.ts
> +    "postId": number,
Остались от скопированного объекта из api

2024-03-27 17:16 UTC, VolffS commented on src/type/i-authorization-user.ts
> +export interface IAuthorizationUser {
Done

2024-03-27 17:19 UTC, VolffS commented on src/components/comment-list/comments-list.tsx
> +                {!isLoading && stateLoader.shutdownLoader()}
Done

2024-03-27 18:20 UTC, merged